format_version: v1.0
type: UniqueComponent
attributes: {id: supc}
children:
- type: Symbols
  children:
  - type: Comment
    attributes: {id: PULSE_WIDTH_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: 'Minimum WKUPx Pulse Width: 0.976 ms ( 32 SLCK Cycles
            )'}
  - type: Boolean
    attributes: {id: SM_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: 'true'}
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: SUPC_SMMR_SMSMPL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_SMMR_SMTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '15'}
  - type: Boolean
    attributes: {id: SUPC_WUIR_WKUPEN7}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT10}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT11}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT12}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT13}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT8}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUIR_WKUPT9}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUMR_LPDBC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: SUPC_WUMR_SMEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: SUPC_WUMR_WKUPDBC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: supc, value: '0'}
      - type: User
        attributes: {value: '2'}
- type: ElementPosition
  attributes: {x: '21', y: '65', id: supc}
