format_version: v1.0
type: UniqueComponent
attributes: {id: qspi}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: QSPISPI_HEADER2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: QSPISPI_SOURCE2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: QSPI_CLK_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** QSPI Clock Frequency Is Set To 15.0 MHz for Master
            Clock Frequency At 150.0 MHz'}
  - type: Integer
    attributes: {id: QSPI_CLK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi, value: '15000000'}
  - type: KeyValueSet
    attributes: {id: QSPI_CPOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi, value: '0'}
  - type: File
    attributes: {id: QSPI_HEADER2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: QSPI_LLBBITS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: QSPI_NBBITS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: QSPI_SCBR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '9'}
  - type: KeyValueSet
    attributes: {id: QSPI_SMM}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: File
    attributes: {id: QSPI_SOURCE1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Hex
    attributes: {id: SPI_DUMMY_DATA}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '255'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi, value: '255'}
- type: ElementPosition
  attributes: {x: '262', y: '135', id: qspi}
