files:
- generatedChecksum: 9D5EE038B893127B787BC03DFA6B467F
  logicalPath: config\sam_e70_xult
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9D5EE038B893127B787BC03DFA6B467F
- generatedChecksum: 27368762F4ED13A284F1602521539A75
  logicalPath: config\sam_e70_xult
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 27368762F4ED13A284F1602521539A75
- generatedChecksum: 2ECFF52751CDC1635241982954F49E6D
  logicalPath: config\sam_e70_xult
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2ECFF52751CDC1635241982954F49E6D
- generatedChecksum: 6513F2461B8F476B68CA73906086047F
  logicalPath: config\sam_e70_xult
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6513F2461B8F476B68CA73906086047F
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8F819EF2D3EA7171FEDD6C261A09B50B
  logicalPath: config\sam_e70_xult\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8F819EF2D3EA7171FEDD6C261A09B50B
- generatedChecksum: 79F1E7691AFEECE298BB94C2E49B1570
  logicalPath: config\sam_e70_xult\peripheral\efc
  name: plib_efc.c
  physicalPath: peripheral\efc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 79F1E7691AFEECE298BB94C2E49B1570
- generatedChecksum: D57F478C7B2DD637FAF8A1F7ED69C2A9
  logicalPath: config\sam_e70_xult\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: D57F478C7B2DD637FAF8A1F7ED69C2A9
- generatedChecksum: A7D9E18B27B6E5D1B30189B83C587E21
  logicalPath: config\sam_e70_xult\peripheral\pio
  name: plib_pio.c
  physicalPath: peripheral\pio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A7D9E18B27B6E5D1B30189B83C587E21
- generatedChecksum: CF61CBE48790F6A05A24634CE8C8E3C3
  logicalPath: config\sam_e70_xult\peripheral\twihs\slave
  name: plib_twihs0_slave.c
  physicalPath: peripheral\twihs\slave
  security: NON_SECURE
  type: SOURCE
  userChecksum: CF61CBE48790F6A05A24634CE8C8E3C3
- generatedChecksum: 3A35F794BD3C19E7B3142ED6806E4EFE
  logicalPath: config\sam_e70_xult
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3A35F794BD3C19E7B3142ED6806E4EFE
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\sam_e70_xult\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: B3C809FA7FFCCC3B71EA8F6CC47D28A8
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: acc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B3C809FA7FFCCC3B71EA8F6CC47D28A8
- generatedChecksum: FDBFD9F75EEBE324AA96C928A6A04B1A
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: aes.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FDBFD9F75EEBE324AA96C928A6A04B1A
- generatedChecksum: DA3D25BC74A1F9D710EAEAE01E09CB6B
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: afec.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DA3D25BC74A1F9D710EAEAE01E09CB6B
- generatedChecksum: EFEDD586248DACAD8B9A0236F399147F
  logicalPath: packs\ATSAME70Q21B_DFP
  name: atsame70q21b.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: EFEDD586248DACAD8B9A0236F399147F
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: E7ED3FC8D0289ABF467A256B128C9D1A
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: chipid.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E7ED3FC8D0289ABF467A256B128C9D1A
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: 8DA90CDFAED934C14DB1E81B104CEE2F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 8DA90CDFAED934C14DB1E81B104CEE2F
- generatedChecksum: 9DAA5BF1D99700676BDD7A9BF97DBBB9
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: dacc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9DAA5BF1D99700676BDD7A9BF97DBBB9
- generatedChecksum: D7E85FB7DCF4885CF01B659BB17B42CA
  logicalPath: config\sam_e70_xult
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: D7E85FB7DCF4885CF01B659BB17B42CA
- generatedChecksum: CF6C57ABBDAB3EBCC189199791FAD50C
  logicalPath: config\sam_e70_xult
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CF6C57ABBDAB3EBCC189199791FAD50C
- generatedChecksum: 9FD18F0D30B89945CC141BA0DE2ABE90
  logicalPath: config\sam_e70_xult
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9FD18F0D30B89945CC141BA0DE2ABE90
- generatedChecksum: 56C5CF9C2C712CAA93EFB1BA10BD1DEB
  logicalPath: config\sam_e70_xult
  name: device_vectors.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 56C5CF9C2C712CAA93EFB1BA10BD1DEB
- generatedChecksum: 0F965FE155AB58FCE4BE9C2A61E13CA2
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: efc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0F965FE155AB58FCE4BE9C2A61E13CA2
- generatedChecksum: FF9E1358AB5A9ED7A6238878D589609B
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: gmac.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FF9E1358AB5A9ED7A6238878D589609B
- generatedChecksum: F004479B3985F06CCFD4DE1A35CA5EB0
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: gpbr.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F004479B3985F06CCFD4DE1A35CA5EB0
- generatedChecksum: 050EE912A4D366C41E0397BA97BDF055
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: hsmci.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 050EE912A4D366C41E0397BA97BDF055
- generatedChecksum: 0F98538EAF8A923ACC797399640D3F48
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: i2sc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0F98538EAF8A923ACC797399640D3F48
- generatedChecksum: 696A901CED4CDCF634ADBC1F38264155
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: icm.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 696A901CED4CDCF634ADBC1F38264155
- generatedChecksum: 26D5E9D22B933813975D2B0B350FB0D9
  logicalPath: config\sam_e70_xult
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 26D5E9D22B933813975D2B0B350FB0D9
- generatedChecksum: 5DC4E80ED75FBEBDA64E862734EA806E
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: isi.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5DC4E80ED75FBEBDA64E862734EA806E
- generatedChecksum: 20C63C1E718889076C082F9455CE2B96
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: matrix.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 20C63C1E718889076C082F9455CE2B96
- generatedChecksum: E2C47EB1000BF87206D66814F110FC6E
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: mcan.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E2C47EB1000BF87206D66814F110FC6E
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: 968031D671812B8066BC8EF46FBED2A3
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: pio.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 968031D671812B8066BC8EF46FBED2A3
- generatedChecksum: BFDB10EBEF4DBDE66563BA7DD136A98F
  logicalPath: config\sam_e70_xult\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: BFDB10EBEF4DBDE66563BA7DD136A98F
- generatedChecksum: FB046CED42CA3B2AE1895C186571EF71
  logicalPath: config\sam_e70_xult\peripheral\efc
  name: plib_efc.h
  physicalPath: peripheral\efc
  security: NON_SECURE
  type: HEADER
  userChecksum: FB046CED42CA3B2AE1895C186571EF71
- generatedChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
  logicalPath: config\sam_e70_xult\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
- generatedChecksum: C35016060DEF1B2807ABEB3D696EF536
  logicalPath: config\sam_e70_xult\peripheral\pio
  name: plib_pio.h
  physicalPath: peripheral\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: C35016060DEF1B2807ABEB3D696EF536
- generatedChecksum: 68E6F92C974FE00B76B8C6B307A56006
  logicalPath: config\sam_e70_xult\peripheral\twihs\slave
  name: plib_twihs0_slave.h
  physicalPath: peripheral\twihs\slave
  security: NON_SECURE
  type: HEADER
  userChecksum: 68E6F92C974FE00B76B8C6B307A56006
- generatedChecksum: 9B39B3197E0721E45A19B11CE0A6CAAD
  logicalPath: config\sam_e70_xult\peripheral\twihs\slave
  name: plib_twihs_slave_common.h
  physicalPath: peripheral\twihs\slave
  security: NON_SECURE
  type: HEADER
  userChecksum: 9B39B3197E0721E45A19B11CE0A6CAAD
- generatedChecksum: DE0F267E3B47C0775756BAD1A572FE8A
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: pmc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DE0F267E3B47C0775756BAD1A572FE8A
- generatedChecksum: E4FCF5F115A397FFA6F5580CA0C07F5A
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: pwm.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E4FCF5F115A397FFA6F5580CA0C07F5A
- generatedChecksum: 831F95392DFA73C934469C7FBA8F0F2B
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: qspi.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 831F95392DFA73C934469C7FBA8F0F2B
- generatedChecksum: 70D1C76F5AE56E5EFAB500DB05D0DBCD
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: rstc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 70D1C76F5AE56E5EFAB500DB05D0DBCD
- generatedChecksum: DE4AD0FFEEACE3CCB834D5DDFC3DA23A
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: rswdt.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DE4AD0FFEEACE3CCB834D5DDFC3DA23A
- generatedChecksum: 33214F6C0D5836DA317D7492CF55A564
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 33214F6C0D5836DA317D7492CF55A564
- generatedChecksum: ABE56900A9A1EF02CAE0567BE350CCE5
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: rtt.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: ABE56900A9A1EF02CAE0567BE350CCE5
- generatedChecksum: 27709FC220811543DC528E9690778C51
  logicalPath: packs\ATSAME70Q21B_DFP\pio
  name: same70q21b.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 27709FC220811543DC528E9690778C51
- generatedChecksum: 5D92DF17E8ABDEB1375FFB0BE4F59BCA
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: sdramc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D92DF17E8ABDEB1375FFB0BE4F59BCA
- generatedChecksum: 10EE310F1D11E5196FEE345181EBFDD9
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: smc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 10EE310F1D11E5196FEE345181EBFDD9
- generatedChecksum: B6CDE24E6F28FB668602E165EC59B608
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: spi.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B6CDE24E6F28FB668602E165EC59B608
- generatedChecksum: 739EE4D3846046487C305EE2CCAABBF4
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: ssc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 739EE4D3846046487C305EE2CCAABBF4
- generatedChecksum: BFBC12D17106A26D0A51A329CE1A2CC5
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: supc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BFBC12D17106A26D0A51A329CE1A2CC5
- generatedChecksum: C96BA321D40C8A2F92C52B18DB669D35
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C96BA321D40C8A2F92C52B18DB669D35
- generatedChecksum: 812B613CCACA9D91D45F77BFA31F1E1F
  logicalPath: config\sam_e70_xult
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 812B613CCACA9D91D45F77BFA31F1E1F
- generatedChecksum: C4D80D71ED9675E381790369F7F0E533
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: trng.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C4D80D71ED9675E381790369F7F0E533
- generatedChecksum: 49D8B2BE48B828EAB9715EB85BF1E28F
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: twihs.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 49D8B2BE48B828EAB9715EB85BF1E28F
- generatedChecksum: 29180AE4124615220D0D0043D0816ED4
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: uart.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 29180AE4124615220D0D0043D0816ED4
- generatedChecksum: 0FC10EC0144A6F28EF2C777FF06C8FF9
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: usart.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0FC10EC0144A6F28EF2C777FF06C8FF9
- generatedChecksum: 527DBBBC5C142DE218ADC40981813BE7
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: usbhs.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 527DBBBC5C142DE218ADC40981813BE7
- generatedChecksum: 66A47EFC74B7CFE70446ED8A12981963
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: utmi.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 66A47EFC74B7CFE70446ED8A12981963
- generatedChecksum: 858228063058DD499413B02C7AF901E3
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 858228063058DD499413B02C7AF901E3
- generatedChecksum: BE8EA4D1F690522A7FF375DBDBC0B95B
  logicalPath: packs\ATSAME70Q21B_DFP\component
  name: xdmac.h
  physicalPath: ..\..\packs\ATSAME70Q21B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BE8EA4D1F690522A7FF375DBDBC0B95B
- generatedChecksum: 9007938AD21A4AE37630C58DB033198B
  logicalPath: config\sam_e70_xult
  name: ATSAME70Q21B.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 9007938AD21A4AE37630C58DB033198B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_e70_xult;../src/packs/ATSAME70Q21B_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_e70_xult;../src/packs/ATSAME70Q21B_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32Global
  delimiter: ''
  key: mdtcm
  security: NON_SECURE
  value: ''
- append: false
  category: C32Global
  delimiter: ''
  key: mitcm
  security: NON_SECURE
  value: ''
- append: false
  category: C32Global
  delimiter: ''
  key: mstacktcm
  security: NON_SECURE
  value: 'false'
sourcePaths: []
