format_version: v1.0
type: UniqueComponent
attributes: {id: twihs0}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: I2C_CLOCK_SPEED}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: I2C_CLOCK_SPEED_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '400000'}
  - type: Integer
    attributes: {id: TWIHS_CLK_SRC_FREQ}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '150000000'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CHDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '177'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CKDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '0'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CLDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '192'}
  - type: File
    attributes: {id: TWIHS_FILE_MAIN_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TWIHS_FILE_MASTER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TWIHS_FILE_SRC_MAIN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: TWIHS_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: TWIHS_OPMODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SLAVE}
  - type: Hex
    attributes: {id: TWIHS_SLAVE_ADDRESS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TWIHS_SLAVE_COMMON_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TWIHS_SLAVE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TWIHS_SLAVE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TWIHS_TIMEOUT_COUNT_VAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs0, value: '60000'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: twihs0}
