format_version: v1.0
type: UniqueComponent
attributes: {id: rtc}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: RTC_MR_OUT0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ALARM_FLAG}
- type: ElementPosition
  attributes: {x: '147', y: '63', id: rtc}
