configName: sam_e70_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME70Q21B
projectName: ''
settings:
  PackageFilter: aerospace;aws_cloud;bootloader;bootloader_apps_uart;bsp;core;core_apps_pic32cm_mc00;core_apps_pic32mk;core_apps_pic32mx;core_apps_pic32mz_da;core_apps_pic32mz_ef;core_apps_pic32mz_w1;core_apps_sam_c20_c21;core_apps_sam_d20;core_apps_sam_d5x_e5x;core_apps_sam_e70_s70_v70_v71;core_apps_sam_ha1;crypto;cryptoauthlib;csp;csp_apps_pic32mz_da;csp_apps_pic32mz_ef;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_ha1;expresslogic_threadx;gfx;gfx_apps;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.3.73\same70b\atdf\ATSAME70Q21B.atdf
