configName: sam_v71_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMV71Q21B
projectName: ''
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.5.1
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAMV71_DFP\4.0.41\samv71b\atdf\ATSAMV71Q21B.atdf
