configName: sam_v71_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMV71Q21B
projectName: ''
settings:
  PackageFilter: aerospace;aws_cloud;bootloader;bsp;bt;core;crypto;cryptoauthlib;cryptoauthlib_apps;csp;ethercat;expresslogic_threadx;gfx;gfx_apps;micrium_ucos3;motor_control;net;touch;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMV71_DFP\4.2.63\samv71b\atdf\ATSAMV71Q21B.atdf
