configName: sam_v71_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMV71Q21B
projectName: ''
settings:
  PackageFilter: aerospace;aws_cloud;bootloader;bootloader_apps_uart;bsp;core;core_apps_pic32mz_da;core_apps_pic32mz_ef;core_apps_sam_d20;core_apps_sam_d5x_e5x;core_apps_sam_e70_s70_v70_v71;crypto;cryptoauthlib;csp;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;expresslogic_threadx;gfx;gfx_apps;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMV71_DFP\4.3.66\samv71b\atdf\ATSAMV71Q21B.atdf
