format_version: v1.0
type: UniqueComponent
attributes: {id: acc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: ACC_MR_EDGETYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: ACC_MR_SELMINUS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: KeyValueSet
    attributes: {id: ACC_MR_SELPLUS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '15', y: '66', id: acc}
