format_version: v1.0
type: UniqueComponent
attributes: {id: cmsis}
children:
- type: Symbols
  children:
  - type: Library
    attributes: {id: CMSIS_DSP_LIB_cortexM7lfdp}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: dest}
        children:
        - {type: Value, value: ../../packs/CMSIS/CMSIS/DSP/Lib/ARM}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: arm_cortexM7lfdp_math.lib}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../../dev_packs/arm/CMSIS/5.8.0/CMSIS/DSP/Lib/ARM/arm_cortexM7lfdp_math.lib}
- type: ElementPosition
  attributes: {x: '120', y: '20', id: cmsis}
