configName: sam_e70_xult_keil
folderName: ''
format_version: v1.0
frameworkPath: D:\Projects\h3
processor: ATSAME70Q21B
projectName: usart_echo_interrupt_sam_e70_xult_keil
settings:
  PackageFilter: bsp;core;csp;net;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.2.62\same70b\atdf\ATSAME70Q21B.atdf
