configName: sam_e70_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME70Q21B
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_rh71;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.3.67\same70b\atdf\ATSAME70Q21B.atdf
