format_version: v1.0
type: UniqueComponent
attributes: {id: tc0}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ENCODER_POS_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: TC0_QuadraturePositionGet}
  - type: String
    attributes: {id: ENCODER_POS_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: ''}
  - type: String
    attributes: {id: ENCODER_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: TC0_QuadratureStart}
  - type: String
    attributes: {id: ENCODER_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: TC0_QuadratureStop}
  - type: Integer
    attributes: {id: TC0_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '1171875'}
  - type: Combo
    attributes: {id: TC0_CMR_ACPA}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: TOGGLE}
  - type: Combo
    attributes: {id: TC0_CMR_ACPC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: NONE}
  - type: KeyValueSet
    attributes: {id: TC0_CMR_TCCLKS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: Menu
    attributes: {id: TC0_COMPARE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Long
    attributes: {id: TC0_COMPARE_A}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '11719'}
    - type: Values
      children:
      - type: User
        attributes: {value: '2929'}
  - type: Long
    attributes: {id: TC0_COMPARE_B}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '11719'}
  - type: Boolean
    attributes: {id: TC0_COMPARE_IER_CPCS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Comment
    attributes: {id: TC0_COMPARE_PERIOD}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Waveform Period is 10000.2133333 uS****'}
  - type: Long
    attributes: {id: TC0_COMPARE_PERIOD_COUNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '11719'}
  - type: Boolean
    attributes: {id: TC0_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Combo
    attributes: {id: TC0_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: COMPARE}
  - type: Boolean
    attributes: {id: TC0_PCK7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Comment
    attributes: {id: TC0_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Clock resolution is 853.333333333 nS****'}
  - type: Menu
    attributes: {id: TC0_TIMER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: TC0_TIMER_PERIOD_CMT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Period Count is 60000****'}
  - type: Float
    attributes: {id: TC0_TIMER_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '55.924053'}
  - type: Integer
    attributes: {id: TC3_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '32000'}
  - type: Boolean
    attributes: {id: TC3_PCK7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Comment
    attributes: {id: TC3_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Clock resolution is 31250.0 nS****'}
  - type: Comment
    attributes: {id: TC_QEI_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Time Base is 469218.75 uS****'}
- type: ElementPosition
  attributes: {x: '31', y: '60', id: tc0}
