configName: sam_e70_xult_iar
folderName: ''
format_version: v1.0
frameworkPath: D:\HARMONY3
processor: ATSAME70Q21B
projectName: twihs_eeprom_sam_e70_xult
settings:
  PackageFilter: bsp;core;csp;net;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.2.62\same70b\atdf\ATSAME70Q21B.atdf
