format_version: v1.0
type: UniqueComponent
attributes: {id: efc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: NVM_RWS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: efc, value: '6'}
- type: ElementPosition
  attributes: {x: '322', y: '146', id: efc}
