format_version: v1.0
type: UniqueComponent
attributes: {id: rstc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: RSTC_MR_URSTEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rstc, value: '0'}
      - type: User
        attributes: {value: '1'}
  - type: String
    attributes: {id: RSTC_RSTTYP_DESC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rstc, value: '["First power-up reset","Return from Backup
            Mode","Watchdog fault occurred","Processor reset required by the software","NRST
            pin detected low"]'}
  - type: String
    attributes: {id: RSTC_RSTTYP_ENUM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rstc, value: '["RSTC_GENERAL_RESET = RSTC_SR_RSTTYP_GENERAL_RST","RSTC_BACKUP_RESET
            = RSTC_SR_RSTTYP_BACKUP_RST","RSTC_WATCHDOG_RESET = RSTC_SR_RSTTYP_WDT_RST","RSTC_SOFTWARE_RESET
            = RSTC_SR_RSTTYP_SOFT_RST","RSTC_USER_RESET = RSTC_SR_RSTTYP_USER_RST"]'}
- type: ElementPosition
  attributes: {x: '19', y: '69', id: rstc}
