format_version: v1.0
type: UniqueComponent
attributes: {id: spi0}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SPI_CSR_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi0, value: '0'}
  - type: Boolean
    attributes: {id: SPI_EN_NPCS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi0, value: 'true'}
  - type: KeyValueSet
    attributes: {id: SPI_MR_PCS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: SPI_NUM_CSR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi0, value: '1'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: spi0}
