format_version: v1.0
type: UniqueComponent
attributes: {id: tc1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ENCODER_POS_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: TC1_QuadraturePositionGet}
  - type: String
    attributes: {id: ENCODER_POS_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: ''}
  - type: String
    attributes: {id: ENCODER_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: TC1_QuadratureStart}
  - type: String
    attributes: {id: ENCODER_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: TC1_QuadratureStop}
  - type: Integer
    attributes: {id: TC2_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: '150000000'}
  - type: Menu
    attributes: {id: TC2_COMPARE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Long
    attributes: {id: TC2_COMPARE_A}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '60000'}
  - type: Long
    attributes: {id: TC2_COMPARE_B}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '60000'}
    - type: Values
      children:
      - type: User
        attributes: {value: '600'}
  - type: Boolean
    attributes: {id: TC2_COMPARE_IER_CPCS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Comment
    attributes: {id: TC2_COMPARE_PERIOD}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Waveform Period is 400.0 uS****'}
  - type: Long
    attributes: {id: TC2_COMPARE_PERIOD_COUNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '60000'}
  - type: Boolean
    attributes: {id: TC2_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Combo
    attributes: {id: TC2_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: COMPARE}
  - type: Comment
    attributes: {id: TC2_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Clock resolution is 6.66666666667 nS****'}
  - type: Menu
    attributes: {id: TC2_TIMER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: TC2_TIMER_PERIOD_CMT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Period Count is 60000****'}
  - type: Integer
    attributes: {id: TC3_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: '150000000'}
  - type: Boolean
    attributes: {id: TC3_PCK7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: 'false'}
- type: ElementPosition
  attributes: {x: '190', y: '58', id: tc1}
